"""Render Terraform import {} blocks from NormalizationContext.import_registry."""
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from importer.normalizer import NormalizationContext

_HEADER = """\
# imports.tf — generated by terraform-dbtcloud-yaml importer
# Requires Terraform >= 1.5
#
# Run 'terraform apply' once to bring existing resources under management.
# After a successful apply, this file can be deleted — resources are now in state.
"""


def generate_import_blocks(context: "NormalizationContext") -> str:
    lines = [_HEADER]
    for entry in context.import_registry:
        lines += ["import {", f'  to = {entry["address"]}', f'  id = "{entry["id"]}"', "}", ""]
    return "\n".join(lines)
